/**
 * ESM entry-point emitter.
 *
 * Loads the compiled addon and re-exports every class and function under exactly
 * the names the addon registers (the §2 invariant). It also links the JS
 * prototype chain between classes so that `child instanceof Parent` holds — the
 * C++ side registers each class independently, so the inheritance relationship
 * is reconstructed here from the IR.
 *
 * Built from generator functions that `yield` lines; {@link generateJs} joins
 * them. Emitted code is tab-indented.
 */

import type { Namespace } from '../ir.js';
import { functionExportNames } from '../names.js';
import { TypeContext } from '../types.js';

type Lines = Generator<string, void, void>;

function* file(ns: Namespace, addonPath: string): Lines {
	const ctx = new TypeContext(ns);
	const classNames = ns.classes.map(c => c.name);
	const functionNames = functionExportNames(ns).map(f => f.jsName);

	yield `// Generated by girbind from ${ns.name}-${ns.version}`;
	yield '// DO NOT EDIT THIS FILE DIRECTLY';
	yield '';
	yield "import { createRequire } from 'node:module';";
	yield '';
	yield `const addon = createRequire(import.meta.url)('${addonPath}');`;
	yield '';

	// Link prototype chains so `instanceof` works across the hierarchy.
	const withParent = ns.classes.filter(c => c.parent && ctx.classes.has(c.parent));
	for (const c of withParent) {
		yield `Object.setPrototypeOf(addon.${c.name}.prototype, addon.${c.parent}.prototype);`;
		yield `Object.setPrototypeOf(addon.${c.name}, addon.${c.parent});`;
	}
	if (withParent.length) yield '';

	yield 'export const {';
	for (const name of classNames) yield `\t${name},`;
	for (const name of functionNames) yield `\t${name},`;
	yield '} = addon;';
	yield '';
	yield 'export default addon;';
}

/**
 * @param ns parsed namespace
 * @param addonPath require path to the built `.node` relative to the entry
 * point. The build step colocates the addon with the JS, so this is normally
 * `./<addon>.node`.
 */
export function generateJs(ns: Namespace, addonPath: string): string {
	return [...file(ns, addonPath)].join('\n') + '\n';
}
