/**
 * TypeScript declaration (`.d.ts`) emitter.
 *
 * Emits one `declare class` per GObject class (using real `extends` to mirror
 * the C++/JS inheritance), enum types, and standalone function declarations.
 * All names come from {@link ../names} so they match the addon's exports exactly.
 *
 * Like the C++ emitter, this is built from generator functions that `yield`
 * lines; {@link generateTs} joins them. Emitted code is tab-indented.
 */

import type { Class, Enumeration, Func, Namespace, Property } from '../ir.js';
import {
	factoryName,
	functionExportNames,
	isSupported,
	methodName,
	primaryConstructor,
	secondaryConstructors,
} from '../names.js';
import { TypeContext } from '../types.js';

type Lines = Generator<string, void, void>;

function memberName(name: string): string {
	return name.replace(/-/g, '_').replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

function* enumDecl(e: Enumeration): Lines {
	yield `export enum ${e.name} {`;
	for (const m of e.members) yield `\t${m.name.toUpperCase()} = ${m.value},`;
	yield '}';
	yield '';
}

function params(ctx: TypeContext, func: Func): string {
	const inParams = func.parameters.filter(p => !p.isInstance && p.direction === 'in' && p.name !== 'error');
	// A param may be syntactically optional (`?`) only if every later param is
	// also optional; otherwise TS rejects "required after optional". A nullable
	// param that precedes a required one stays required but accepts `| null`.
	// `optionalFrom` is the index of the first param in the trailing run of
	// nullable params (= length when there is no such run).
	let optionalFrom = inParams.length;
	while (optionalFrom > 0 && inParams[optionalFrom - 1].nullable) optionalFrom--;
	return inParams
		.map((p, i) => {
			const name = memberName(p.name);
			const type = ctx.tsType(p.type);
			const optional = p.nullable && i >= optionalFrom;
			return `${name}${optional ? '?' : ''}: ${type}${p.nullable ? ' | null' : ''}`;
		})
		.join(', ');
}

function ret(ctx: TypeContext, func: Func): string {
	const rv = func.returnValue;
	if (rv.type.girType === 'none') return 'void';
	const base = ctx.tsType(rv.type);
	return rv.nullable ? `${base} | null` : base;
}

function* accessor(ctx: TypeContext, p: Property): Lines {
	const type = ctx.tsType(p.type);
	if (p.readable) yield `get ${memberName(p.name)}(): ${type};`;
	if (p.writable) yield `set ${memberName(p.name)}(value: ${type});`;
}

function* classDecl(ctx: TypeContext, cls: Class): Lines {
	const ext = cls.parent && ctx.classes.has(cls.parent) ? ` extends ${cls.parent}` : '';
	yield `export declare class ${cls.name}${ext} {`;

	const primary = primaryConstructor(cls.constructors);
	// `protected` (not `private`) so subclasses can still `extends` a return-only
	// base; the runtime constructor throws for these classes regardless.
	yield primary && isSupported(primary) ? `\tconstructor(${params(ctx, primary)});` : '\tprotected constructor();';

	for (const f of secondaryConstructors(cls.constructors).filter(isSupported)) {
		yield `\tstatic ${factoryName(f)}(${params(ctx, f)}): ${cls.name};`;
	}
	for (const f of cls.staticMethods.filter(isSupported)) {
		yield `\tstatic ${methodName(f)}(${params(ctx, f)}): ${ret(ctx, f)};`;
	}
	for (const f of cls.methods.filter(isSupported)) {
		yield `\t${methodName(f)}(${params(ctx, f)}): ${ret(ctx, f)};`;
	}
	// Skip a property whose name collides with a method/static already declared
	// here — the method wins; emitting both is a duplicate identifier.
	const taken = new Set([...cls.methods, ...cls.staticMethods].filter(isSupported).map(methodName));
	for (const p of cls.properties) {
		if (taken.has(memberName(p.name))) continue;
		for (const line of accessor(ctx, p)) yield `\t${line}`;
	}

	yield '}';
	yield '';
}

function* file(ns: Namespace): Lines {
	const ctx = new TypeContext(ns);
	yield `// Generated by girbind from ${ns.name}-${ns.version}`;
	yield '// DO NOT EDIT THIS FILE DIRECTLY';
	yield '';
	for (const e of ns.enumerations) yield* enumDecl(e);
	for (const cls of ns.classes) yield* classDecl(ctx, cls);
	for (const { func, jsName } of functionExportNames(ns)) {
		yield `export declare function ${jsName}(${params(ctx, func)}): ${ret(ctx, func)};`;
	}
}

export function generateTs(ns: Namespace): string {
	return [...file(ns)].join('\n') + '\n';
}
